version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo-franquicia
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: franquicia_db
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: franquicia-app
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/franquicia_db
    ports:
      - "8080:8080"

volumes:
  mongo_data: